name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Build the files'
      working-directory: ./
      run: |
        cmake CMakeLists.txt
    - name: 'Make the files'
      working-directory: ./temp
      run: |
        make
    - name: 'Execute the files'
      working-directory: ./temp
      run: echo "Done!"
