name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'List files'
      run: |
        ls /
    - name: 'Build the files'
      run: |
        cmake /CMakeLists.txt
    - name: 'Make the files'
      run: |
        make
    - name: 'Execute the files'
      run: echo "Done!"
